### PR TITLE
Fix color issues and failing tests

### PR DESCRIPTION
**Pull request by mason-stewart**
Hey there!

I installed this generator this morning, but noticed it was failing on the `yellow.bold` call at https://github.com/danheberden/yeoman-generator-requirejs/blob/master/app/index.js#L30. 

Even after bumping the dependencies, as suggested [here](https://github.com/yeoman/generator-webapp/issues/137), the error was still occurring, so I used chalk, just as was done in [this commit](https://github.com/yeoman/generator/commit/3c60110). Fixed!

After that, I ran the specs and saw failures. The 3rd and 4th commits in this PR address this, but I'm a little iffy on them. In both of those commits, I couldn't (after a cursory search) track down what repo or change was actually responsible for breaking them (I'm assuming the two specs were passing before?). The fourth commit especially seems heavy-handed, as it just removes error checking, but I did take a cue from the webapp generator where [they only expect an answer object](https://github.com/yeoman/generator-webapp/blob/master/app/index.js#L64) in their prompt.

Happy to help/refactor/whatever, just let me know. Both tests passing locally and generators works just fine for me now on OS X 10.8.4. Thanks!

### CODE REVIEW

**Comment by vitorbaptista** [comment]
:+1: 

Had this same issue, and this PR fixed it.

**Comment by b-long** [comment]
Assuming I can get this to work, I'd really like to see this PR merged :)  Howerver, I can't seem to avoid  output like this when I run `grunt qunit` :

``` shell
me@home:~/test-pr/GENERATED-SITE$ grunt qunit --force -v
Initializing
Command-line options: --force, --verbose

Reading "Gruntfile.js" Gruntfile...OK

Registering Gruntfile tasks.
Reading package.json...OK
Parsing package.json...OK
Initializing config...OK

Registering "grunt-contrib-clean" local Npm module tasks.
Reading /home/me/test-pr/GENERATED-SITE/node_modules/grunt-contrib-clean/package.json...OK
Parsing /home/me/test-pr/GENERATED-SITE/node_modules/grunt-contrib-clean/package.json...OK
Loading "clean.js" tasks...OK
+ clean

Registering "grunt-contrib-concat" local Npm module tasks.
Reading /home/me/test-pr/GENERATED-SITE/node_modules/grunt-contrib-concat/package.json...OK
Parsing /home/me/test-pr/GENERATED-SITE/node_modules/grunt-contrib-concat/package.json...OK
Loading "concat.js" tasks...OK
+ concat

Registering "grunt-contrib-uglify" local Npm module tasks.
Reading /home/me/test-pr/GENERATED-SITE/node_modules/grunt-contrib-uglify/package.json...OK
Parsing /home/me/test-pr/GENERATED-SITE/node_modules/grunt-contrib-uglify/package.json...OK
Loading "uglify.js" tasks...OK
+ uglify

Registering "grunt-contrib-qunit" local Npm module tasks.
Reading /home/me/test-pr/GENERATED-SITE/node_modules/grunt-contrib-qunit/package.json...OK
Parsing /home/me/test-pr/GENERATED-SITE/node_modules/grunt-contrib-qunit/package.json...OK
Loading "qunit.js" tasks...OK
+ qunit

Registering "grunt-contrib-jshint" local Npm module tasks.
Reading /home/me/test-pr/GENERATED-SITE/node_modules/grunt-contrib-jshint/package.json...OK
Parsing /home/me/test-pr/GENERATED-SITE/node_modules/grunt-contrib-jshint/package.json...OK
Loading "jshint.js" tasks...OK
+ jshint

Registering "grunt-contrib-watch" local Npm module tasks.
Reading /home/me/test-pr/GENERATED-SITE/node_modules/grunt-contrib-watch/package.json...OK
Parsing /home/me/test-pr/GENERATED-SITE/node_modules/grunt-contrib-watch/package.json...OK
Loading "watch.js" tasks...OK
+ watch

Registering "grunt-contrib-requirejs" local Npm module tasks.
Reading /home/me/test-pr/GENERATED-SITE/node_modules/grunt-contrib-requirejs/package.json...OK
Parsing /home/me/test-pr/GENERATED-SITE/node_modules/grunt-contrib-requirejs/package.json...OK
Loading "requirejs.js" tasks...OK
+ requirejs

Registering "grunt-contrib-connect" local Npm module tasks.
Reading /home/me/test-pr/GENERATED-SITE/node_modules/grunt-contrib-connect/package.json...OK
Parsing /home/me/test-pr/GENERATED-SITE/node_modules/grunt-contrib-connect/package.json...OK
Loading "connect.js" tasks...OK
+ connect
Loading "Gruntfile.js" tasks...OK
+ default, preview, preview-live

Running tasks: qunit

Running "qunit" task

Running "qunit:files" (qunit) task
Verifying property qunit.files exists in config...OK
Files: test/index.html -> files

Testing test/index.html 

Warning: PhantomJS timed out, possibly due to a missing QUnit start() call. Used --force, continuing.
Warning: 0/0 assertions ran (0ms) Used --force, continuing.

Done, but with warnings.

```

**Comment by mason-stewart** [comment]
@b-long are you trying to run the generator's specs? I ran them with `grunt test`, which ran them using Mocha. Can you explain what you're using QUnit for here?

**Comment by b-long** [comment]
@masondesu Sorry, I should have been more clear.  This output is from running the tests _in the generated RequireJS app_ .  I haven't actually looked into the generator's source (or it's tests), I take it Mocha is used?

**Comment by garryyao** [comment]
Would u merge first the color fix and leave this issue open for the tests failures?

**Comment by b-long** [comment]
:+1:

**Comment by mason-stewart** [comment]
@b-long I'm not clear on whether or not this PR is messing up the generated app's qunit specs.

I will say that the specs pass for me when I open the `index.html` in the generated app's test folder in a browser, although you'll want to change the url's of the components. Your index file will need to look like this:

``` html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Test Suite</title>
  <!-- Load local QUnit. -->
  <link rel="stylesheet" href="../bower_components/qunit/qunit/qunit.css" media="screen">
  <script src="../bower_components/qunit/qunit/qunit.js"></script>
  <script>
    QUnit.config.autostart = false;
  </script>

  <script data-main="../app/config" src="../bower_components/requirejs/require.js"></script> 
  <script>
    window.requireTestMode = true;
    require.config({
      deps: ["tests.js"]
    });
  </script>
</head>
<body>
  <div id="qunit"></div>
  <div id="qunit-fixture">
    <!-- fixtures go here -->
  </div>
</body>
</html>
```

I just commited those changes to this branch. Whether these tests were working previously via `grunt qunit` is unclear, but I'm getting the same output in the terminal as you, @b-long.  @danheberden care to chime in on this?

**Comment by mason-stewart** [comment]
Ah, here's a clue to the tests failing in the console: 38fd5132e389434989c2918ef6a4b2e86e388808

Seems like the tests don't work out of the box for everyone?

**Comment by danheberden** [comment]
I think this was due to the older deps? Or if the phantom install didn't work/complete when qunit was installed? If this persists, it should be a new issue and we should check for the presence of phantomjs.

**Comment by dailystore** [comment]
@masondesu Newbie question, what does "window.requireTestMode" mean? I google it but hopeless, no result found. Can you help me figure it out? or some reference documents please? Thank you.

**Comment by mason-stewart** [comment]
@dailystore I assume you're referring to these two lines?

https://github.com/danheberden/yeoman-generator-requirejs/blob/master/app/templates/test/index.html#L15
https://github.com/danheberden/yeoman-generator-requirejs/blob/master/app/templates/app/config.js#L10

I think it's probably just a global var that @danheberden created, rather than something built into require/phantom/etc. Probably best to open a new issue for further discussion on this, though, since this discussion was around this PR and other issues :)

**Pull request merged**
