### PR TITLE
Use `bower_components` directory

### PR DESCRIPTION
**Pull request by singingwolfboy**
The bower project is now using a `bower_components` directory, so this generator should adopt that convention. This pull request also updates the license URL to a better default (fixes issue #2), and documents the phantomJS dependency.

### CODE REVIEW

**Comment by danheberden** [comment]
I wonder if it'd be worth checking bower versions for this and changing the directory accordingly?

**Comment by singingwolfboy** [comment]
Re: checking bower versions: that seems overcomplicated. It may be worthwhile to check for the existence of a `bower_components` directory, and fall back on `components`, but I'm not sure exactly how you would do that, and it would still probably be overcomplicated. Simpler is better.

**Comment by danheberden** [comment]
Well, let's plan on going with the update and then see if it's worth updating to check dependent of versions; at least we'll be mainstream, heh. Thanks for the contribution; seriously awesome/super-helpful.

**Comment by b-long** [comment]
Any update on this Dan?  I noticed `bower_components` seems to be the standard nowadays.

**Comment by danheberden** [comment]
My apologies - I was being a jerk and not paying attention to this repo :(

**Pull request merged**
